# This file is part of the plugin-test project.
lang: "de-DE"

# The language code for the plugin. This is used to determine the language of the plugin.
# The default language is English (en-US).
# You can change this to any other language code supported by the plugin.

# The plugin will use this language code to load the appropriate language file.
# If you want to add a new language, you can create a new file in the `lang` directory with the appropriate language code.

# Example: If you want to use French, you can set this to "fr-FR".
# If you want to use Spanish, you can set this to "es-ES".

settings:
  # The settings for the plugin.
  # You can add any settings you want here.
  # The plugin will use these settings to configure itself.

  # Example: If you want to enable a feature, you can set it to true.
  enableFeature: true

  funnynames:
    - "LustigerName1"
    - "LustigerName2"
    - "LustigerName3"

items:
  - name: "Schwert"
    id: 276
    price: 15.99
    lore:
      - "Ein mächtiges Schwert"
      - "Geschmiedet in den Tiefen der Erde"
  - name: "Schild"
    id: 311
    price: 10.49
    lore:
      - "Ein starker Schild"
      - "Schützt vor Angriffen"


advanceditems:
  magicwand:
    id: 280
    power: 50
    description:
      - "Eine Zauberstab voller Magie"
      - "Kann mächtige Zauber wirken"
  healingpotion:
    id: 373
    healingAmount: 20
    description:
      - "Ein Trank zur Heilung"
      - "Stellt Gesundheit wieder her"